### ISSUE TITLE
docker compose not working

### ISSUE THREAD

**Issue by retpoline** [livegrep/livegrep.com#5] opened 2019-10-15 16:55 UTC
After a git clone and changing to the /livegrep.com/compose directory to do a docker-compose...

```
$ docker-compose up -d
Creating network "compose_default" with the default driver
Creating volume "compose_livegrep-data" with default driver
Creating volume "compose_caddy" with default driver
Pulling livegrep-backend-linux (docker.io/livegrep/base:75b59048df-0)...
Trying to pull repository docker.io/livegrep/base ... 
ERROR: received unexpected HTTP status: 503 Service Unavailable
```

Is the syntax OK? Or is the image missing or unavailable?

Thanks!

**Comment by nelhage** [comment] 2019-10-27 16:28
That looks like a server error from docker hub. It just worked for me in my testing, can you still reproduce this failure?

**Comment by nelhage** [comment] 2019-10-27 16:28
Closing out, feel free to reopen if you're still seeing this.

**Closed as completed by nelhage** 2019-10-27 16:28 UTC
